### ISSUE TITLE
Exception thrown when generating HTML content in PHP 8

### ISSUE THREAD

**Issue by lsgs** [lsgs/redcap-event-navigation-tweaks#7]
The 'event_navigation_tweaks' module threw the following exception when calling the hook method 'redcap_data_entry_form_top':

TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/modules/event_navigation_tweaks_v1.0.0/EventNavigationTweaks.php:111
Stack trace:
#0 /var/www/html/modules/event_navigation_tweaks_v1.0.0/EventNavigationTweaks.php(111): array_key_exists('caregiver_burde...', NULL)
#1 /var/www/html/modules/event_navigation_tweaks_v1.0.0/EventNavigationTweaks.php(18): MCRI\EventNavigationTweaks\EventNavigationTweaks->makeEventNavPopoverContent('inquiry_form')
#2 /var/www/html/redcap_v13.4.0/ExternalModules/classes/ExternalModules.php(3133): MCRI\EventNavigationTweaks\EventNavigationTweaks->redcap_data_entry_form_top(...

**Comment by lsgs** [comment]
Fixed with [releases/tags/1.1.1](https://github.com/lsgs/redcap-event-navigation-tweaks/releases/tag/1.1.1)
