### ISSUE TITLE
TypeError in_array() null given

### ISSUE THREAD

**Issue by botsmack** [lsgs/redcap-event-navigation-tweaks#9]
We're running Event Navigation Tweaks - v1.1.2 on REDCap 14.6.1 and attempted to upgrade to PHP 8.1, but we're getting a similar error as #8.

```The 'event_navigation_tweaks' module threw the following exception when calling the hook method 'redcap_data_entry_form_top':

TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /public_html/modules/event_navigation_tweaks_v1.1.2/EventNavigationTweaks.php:130
Stack trace:
#0 /public_html/modules/event_navigation_tweaks_v1.1.2/EventNavigationTweaks.php(130): in_array()
#1 /public_html/modules/event_navigation_tweaks_v1.1.2/EventNavigationTweaks.php(114): MCRI\EventNavigationTweaks\EventNavigationTweaks->makeNavRow()
#2 /public_html/modules/event_navigation_tweaks_v1.1.2/EventNavigationTweaks.php(18): MCRI\EventNavigationTweaks\EventNavigationTweaks->makeEventNavPopoverContent()
#3 /public_html/redcap_v14.6.1/ExternalModules/classes/ExternalModules.php(3156): MCRI\EventNavigationTweaks\EventNavigationTweaks->redcap_data_entry_form_top()
#4 /public_html/redcap_v14.6.1/ExternalModules/classes/ExternalModules.php(3323): ExternalModules\ExternalModules::startHook()
#5 /public_html/redcap_v14.6.1/ExternalModules/classes/ExternalModules.php(3356): ExternalModules\ExternalModules::ExternalModules\{closure}()
#6 /public_html/redcap_v14.6.1/Classes/Hooks.php(41): ExternalModules\ExternalModules::callHook()
#7 /public_html/redcap_v14.6.1/DataEntry/index.php(535): Hooks::call()
#8 {main}

**Comment by lsgs** [comment]
Thanks for the report @botsmack. I've put in a check for this and done a new release (v1.1.3) to the REDCap repo. I'll close this now, but do please open a new issue if you come across further problems.
